name: Docker

on:
  push:
    tags:
      - v*
  workflow_dispatch:
    inputs:
      docker_tag: 
         description: Docker Tag
         required: false
jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
      with:
        egress-policy: audit

    - name: Checkout code
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

    - name: Set up QEMU
      uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7 # v2.2.0

    - name: Set up Docker Buildx
      uses: step-security/setup-buildx-action@8c8aef2d414c0b66518fee2b7084e0986f82d7ac # v3.11.1

    - name: Docker login
      uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Set env
      run: |
        echo "DOCKER_TAG=$(echo $GITHUB_REF_NAME | cut -c 2-)" >> $GITHUB_ENV

    # Commenting below targets as we are verifying the difference between snyk cli and snyk website results
    #
    # - name: Set up Snyk CLI
    #   uses: snyk/actions/setup@cdb760004ba9ea4d525f2e043745dfe85bb9077e
    #   with:
    #       snyk-version: v1.1297.3

    # - name: Authenticate Snyk
    #   run: snyk auth ${{ secrets.SNYK_TOKEN }}

    # - name: Run Vulnerability Scan
    #   run: |
    #      make vulnerability-scan

    # - name: Run Container Vulnerability Scan
    #   run: |
    #      make vulnerability-scan-container

    - name: Build and push
      run: |
        if [  "${{ github.event.inputs.docker_tag }}" == "" ]; then
            echo "Creating Docker Images with given Docker Tag  with GITHUB_REF_NAME - ".${{ env.DOCKER_TAG }}
            make VERSION=${{ env.DOCKER_TAG }} release-docker-multi-arch
        else
            echo "Creating Docker Images with Input Docker Tag value ".${{ github.event.inputs.docker_tag }}
            make VERSION=${{  github.event.inputs.docker_tag }} release-docker-multi-arch
        fi        
            